name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:

  schedule:
    - cron: '5 * * * *'

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-core dbt-snowflake

      - name: Run dbt
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          DATABASE: ${{ secrets.DATABASE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ROLE: ${{ secrets.ROLE }}
          SCHEMA: ${{ secrets.SCHEMA }}
        run: |
          dbt test --target prod
          dbt run --select b_mock_data --target prod
          
